//! A faithful model of the SAP-1 ("Simple As Possible 1") computer
//! from the textbooks and the BEN-EATER series, built entirely from
//! the hardware primitives in this project.
//!
//! *Instructions* (single-byte; the high nibble is the opcode, the low
//! nibble is the memory operand):
//!
//! +-----------------+------+---------------------------------------------+
//! | Binary opcode   | Hex  | Instruction            (operand is addressed |
//! +=================+======+=====================+========================+
//! | 0000            | 0    | NOP : no operation                          |
//! | 0001            | 1    | LDA  : A <- MEM[operand]                    |
//! | 0010            | 2    | ADD  : A <- A + MEM[operand]                |
//! | 0011            | 3    | SUB  : A <- A - MEM[operand]                |
//! | 0100            | 4    | STA  : MEM[operand] <- A                    |
//! | 0101            | 5    | LDI  : A <- constant (the operand)          |
//! | 0110            | 6    | JMP  : PC <- operand                        |
//! | 0111            | 7    | JZ   : PC <- operand if ACC == 0            |
//! | 1000            | 8    | JC   : PC <- operand if CARRY == 1          |
//! | 1111            | F    | HLT  : halt the computer                    |
//! +-----------------+------+---------------------------------------------+

use crate::arithmetic::AluSap1;
use crate::decoder::Decoder4to16;
use crate::gates::{AndGate, OrGate};
use crate::hardware::{bus8, Bit, Component, HardwareError, Nmos, Signal};
use crate::latches::{OneHotCounter6Bits, SRLatch};
use crate::memory::{ProgramCounter4Bits, Ram256Bits, Register8Bits, RAM_REGISTERS};
use crate::utils::{bits_to_int, int_to_bits};

/// Control signals generated by the Control Unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ControlSignals {
    /// Program counter out (drives the bus).
    pub co: Bit,
    /// Memory address register in.
    pub mi: Bit,
    /// Program counter count enable.
    pub ce: Bit,
    /// RAM out (drives the bus).
    pub ro: Bit,
    /// Instruction register in.
    pub ii: Bit,
    /// Instruction register out (operand to the bus).
    pub io: Bit,
    /// Accumulator in.
    pub ai: Bit,
    /// Accumulator out (drives the bus / ALU input A).
    pub ao: Bit,
    /// ALU sum out (drives the bus, also the ALU `load` input).
    pub eo: Bit,
    /// ALU subtract.
    pub su: Bit,
    /// B register in.
    pub bi: Bit,
    /// Flags in.
    pub fi: Bit,
    /// Jump (program counter load).
    pub j: Bit,
    /// RAM in.
    pub ri: Bit,
    /// Halt.
    pub hlt: Bit,
}

/// Control Unit for the SAP-1 computer.
///
/// Decodes the current micro-state (T-states from the sequencer), the
/// 4-bit opcode (from the instruction register), and the ALU flags to
/// generate the control signals entirely using logic gates.
#[derive(Debug, Default)]
pub struct ControlUnit {
    decoder: Decoder4to16,

    // Memory instructions: LDA (1), ADD (2), SUB (3), STA (4)
    or_1_2: OrGate,
    or_3_4: OrGate,
    or_mem: OrGate,

    // T3 memory address loading (MI)
    and_t3_mem: AndGate,
    or_mi: OrGate,

    // RAM read operations: T4 with LDA (1), ADD (2), SUB (3)
    or_2_3: OrGate,
    or_1_2_3: OrGate,
    and_t4_read: AndGate,
    or_ro: OrGate,

    // RAM write: T4 with STA (4)
    and_ri: AndGate,

    // Accumulator out: T4 with STA (4)
    and_ao: AndGate,

    // B register in: T4 with ADD (2) or SUB (3)
    and_bi: AndGate,

    // Accumulator in:
    // T3 with LDI (5), T4 with LDA (1), T5 with ADD (2) or SUB (3)
    and_t3_ldi: AndGate,
    and_t4_lda: AndGate,
    and_t5_alu: AndGate,
    or_ai_sub: OrGate,
    or_ai: OrGate,

    // ALU sum out, subtract, flags in: T5 with ADD (2) or SUB (3)
    and_eo: AndGate,
    and_su: AndGate,
    and_fi: AndGate,

    // Jumps: JMP (6), JZ (7) & zero, JC (8) & carry
    and_jz: AndGate,
    and_jc: AndGate,
    or_jz_jc: OrGate,
    or_jump: OrGate,
    and_j: AndGate,

    // Instruction register out (IO):
    // T3 with memory instructions, LDI (5), or jumps
    or_io_target1: OrGate,
    or_io_target2: OrGate,
    and_io: AndGate,

    // Halt: T3 with HLT (15)
    and_hlt: AndGate,
}

impl ControlUnit {
    /// Generate the control signals for one micro-state.
    pub fn control_signals(
        &self,
        t_states: &[Bit; 6],
        opcode: &[Bit; 4],
        carry_flag: Bit,
        zero_flag: Bit,
    ) -> Result<ControlSignals, HardwareError> {
        let [t0, t1, t2, t3, t4, t5] = *t_states;

        let i = self.decoder.compute(opcode)?;

        // Memory instruction mask: LDA (1) | ADD (2) | SUB (3) | STA (4)
        let is_mem = self.or_mem.compute(&[
            self.or_1_2.compute(&[i[1], i[2]])?[0],
            self.or_3_4.compute(&[i[3], i[4]])?[0],
        ])?[0];

        // Jump conditions
        let jz_active = self.and_jz.compute(&[i[7], zero_flag])?[0];
        let jc_active = self.and_jc.compute(&[i[8], carry_flag])?[0];
        let jump_active = self
            .or_jump
            .compute(&[i[6], self.or_jz_jc.compute(&[jz_active, jc_active])?[0]])?[0];

        let or_2_3 = self.or_2_3.compute(&[i[2], i[3]])?[0];

        // Control signals.
        //
        // CO, CE and II are direct wires from the one-hot T-state
        // lines (T0 -> CO, T1 -> CE, T2 -> II). A one-hot line has a
        // single driver — the sequencer flip-flop — so wiring a
        // control line to it is plain fan-out: no `wire` resolution
        // is needed, and every consumer of `co` is wired to the very
        // same net as `t0`.
        let co = t0;
        let mi = self
            .or_mi
            .compute(&[t0, self.and_t3_mem.compute(&[t3, is_mem])?[0]])?[0];
        let ce = t1;

        let ro_read = self
            .and_t4_read
            .compute(&[t4, self.or_1_2_3.compute(&[i[1], or_2_3])?[0]])?[0];
        let ro = self.or_ro.compute(&[t2, ro_read])?[0];

        let ii = t2;

        let io_active = self
            .or_io_target2
            .compute(&[is_mem, self.or_io_target1.compute(&[i[5], jump_active])?[0]])?[0];
        let io = self.and_io.compute(&[t3, io_active])?[0];

        let t3_ldi = self.and_t3_ldi.compute(&[t3, i[5]])?[0];
        let t4_lda = self.and_t4_lda.compute(&[t4, i[1]])?[0];
        let t5_alu = self.and_t5_alu.compute(&[t5, or_2_3])?[0];
        let ai = self
            .or_ai
            .compute(&[t3_ldi, self.or_ai_sub.compute(&[t4_lda, t5_alu])?[0]])?[0];

        let ao = self.and_ao.compute(&[t4, i[4]])?[0];
        let eo = self.and_eo.compute(&[t5, or_2_3])?[0];
        let su = self.and_su.compute(&[t5, i[3]])?[0];
        let bi = self.and_bi.compute(&[t4, or_2_3])?[0];
        let fi = self.and_fi.compute(&[t5, or_2_3])?[0];
        let j = self.and_j.compute(&[t3, jump_active])?[0];
        let ri = self.and_ri.compute(&[t4, i[4]])?[0];
        let hlt = self.and_hlt.compute(&[t3, i[15]])?[0];

        Ok(ControlSignals {
            co,
            mi,
            ce,
            ro,
            ii,
            io,
            ai,
            ao,
            eo,
            su,
            bi,
            fi,
            j,
            ri,
            hlt,
        })
    }
}

impl Component for ControlUnit {
    const INPUTS: usize = 12;
    const OUTPUTS: usize = 15;

    /// Inputs:
    ///
    /// - 0..6:   T-states, one-hot, T0 first
    /// - 6..10:  opcode, least significant bit first
    /// - 10:     carry flag
    /// - 11:     zero flag
    ///
    /// Outputs (in that order):
    ///
    ///     co, mi, ce, ro, ii, io, ai, ao, eo, su, bi, fi, j, ri, hlt
    fn conduct_into(&self, inputs: &[Signal], outputs: &mut [Signal]) -> Result<(), HardwareError> {
        if inputs.len() != Self::INPUTS {
            return Err(HardwareError::InvalidInputCount {
                expected: Self::INPUTS,
                actual: inputs.len(),
            });
        }
        if outputs.len() != Self::OUTPUTS {
            return Err(HardwareError::InvalidInputCount {
                expected: Self::OUTPUTS,
                actual: outputs.len(),
            });
        }

        let mut bits = [Bit::Low; Self::INPUTS];

        for (bit, signal) in bits.iter_mut().zip(inputs.iter()) {
            *bit = Bit::try_from(*signal)?;
        }

        let t_states: [Bit; 6] = bits[0..6].try_into().expect("six T-states");
        let opcode: [Bit; 4] = bits[6..10].try_into().expect("four opcode bits");

        let signals = self.control_signals(&t_states, &opcode, bits[10], bits[11])?;

        outputs.copy_from_slice(
            &[
                signals.co,
                signals.mi,
                signals.ce,
                signals.ro,
                signals.ii,
                signals.io,
                signals.ai,
                signals.ao,
                signals.eo,
                signals.su,
                signals.bi,
                signals.fi,
                signals.j,
                signals.ri,
                signals.hlt,
            ]
            .map(Signal::from),
        );

        Ok(())
    }

    fn transistor_count(&self) -> usize {
        let and_gates = [
            self.and_t3_mem.transistor_count(),
            self.and_t4_read.transistor_count(),
            self.and_ri.transistor_count(),
            self.and_ao.transistor_count(),
            self.and_bi.transistor_count(),
            self.and_t3_ldi.transistor_count(),
            self.and_t4_lda.transistor_count(),
            self.and_t5_alu.transistor_count(),
            self.and_eo.transistor_count(),
            self.and_su.transistor_count(),
            self.and_fi.transistor_count(),
            self.and_jz.transistor_count(),
            self.and_jc.transistor_count(),
            self.and_j.transistor_count(),
            self.and_io.transistor_count(),
            self.and_hlt.transistor_count(),
        ]
        .iter()
        .sum::<usize>();

        let or_gates = [
            self.or_1_2.transistor_count(),
            self.or_3_4.transistor_count(),
            self.or_mem.transistor_count(),
            self.or_mi.transistor_count(),
            self.or_2_3.transistor_count(),
            self.or_1_2_3.transistor_count(),
            self.or_ro.transistor_count(),
            self.or_ai_sub.transistor_count(),
            self.or_ai.transistor_count(),
            self.or_jz_jc.transistor_count(),
            self.or_jump.transistor_count(),
            self.or_io_target1.transistor_count(),
            self.or_io_target2.transistor_count(),
        ]
        .iter()
        .sum::<usize>();

        self.decoder.transistor_count() + and_gates + or_gates
    }
}

/// A simple-as-possible computer.
///
/// The public interface is:
///
///     let mut cpu = Sap1::default();
///     cpu.load_program(&program)?;
///     cpu.run(1000)?;
///     let accumulator = cpu.out();
///
/// `halted`
///     Becomes true once a HLT instruction is read.
///
/// `out`
///     The accumulator content, LSB first.
///
/// This machine is intentionally not a [`Component`]: it is a full
/// sequential computer, not a single combinational function.
#[derive(Debug, Default)]
pub struct Sap1 {
    program_counter: ProgramCounter4Bits,
    memory_address: Register8Bits,
    instruction_register: Register8Bits,
    accumulator: Register8Bits,
    b_register: Register8Bits,
    alu: AluSap1,
    ram: Ram256Bits,
    sequencer: OneHotCounter6Bits,
    control_unit: ControlUnit,

    // Carry and zero flags, stored between micro-states.
    carry_flag: Register8Bits,
    zero_flag: Register8Bits,

    // Bus drivers: NMOS tri-state rows for the program counter, the
    // instruction register and the accumulator. The RAM drives the
    // bus through its own decoder, save AND gates and tri-state rows
    // (see [`Ram256Bits`]), so no duplicated read circuit lives in
    // the CPU.
    pc_bus_nmos: [Nmos; 8],
    ir_bus_nmos: [Nmos; 8],
    acc_bus_nmos: [Nmos; 8],

    // Clock control gates
    pc_or: OrGate,
    pc_and: AndGate,
    halt_latch: SRLatch,
    halt_and: AndGate,

    halted: bool,
    clock_signal: Bit,
}

impl Sap1 {
    /// Becomes true once a HLT instruction has been executed.
    pub fn halted(&self) -> bool {
        self.halted
    }

    /// The current value of the shared clock.
    pub fn clock(&self) -> Bit {
        self.clock_signal
    }

    /// The accumulator content, LSB first.
    pub fn out(&self) -> [Bit; 8] {
        self.accumulator.state()
    }

    /// The current position of the sequencer, T0 first.
    pub fn sequencer_state(&self) -> [Bit; 6] {
        self.sequencer.state()
    }

    /// The program counter value.
    pub fn program_counter_value(&self) -> u8 {
        bits_to_int(&self.program_counter.state()[0..4], false)
    }

    /// The instruction currently stored in the instruction register.
    pub fn current_instruction(&self) -> u8 {
        bits_to_int(&self.instruction_register.state(), false)
    }

    /// The RAM content, in address order.
    pub fn ram_contents(&self) -> [[Bit; 8]; RAM_REGISTERS] {
        self.ram.state()
    }

    /// The number of flags stored by the ALU (carry, zero), LSB first.
    pub fn flags(&self) -> (Bit, Bit) {
        (self.carry_flag.state()[0], self.zero_flag.state()[0])
    }

    /// Toggle the shared clock and return the new value.
    pub fn clock_tick(&mut self) -> Result<Bit, HardwareError> {
        if self.halted {
            return Ok(self.clock_signal);
        }

        self.clock_signal = match self.clock_signal {
            Bit::Low => Bit::High,
            Bit::High => Bit::Low,
        };
        self.update_at(self.clock_signal)?;

        Ok(self.clock_signal)
    }

    /// Update the internal circuit state with the current clock.
    pub fn update(&mut self) -> Result<(), HardwareError> {
        self.update_at(self.clock_signal)
    }

    /// Advance the sequencer by one micro-state and execute it.
    pub fn micro_step(&mut self) -> Result<(), HardwareError> {
        if self.halted {
            return Ok(());
        }

        if self.clock_signal == Bit::High {
            self.clock_tick()?;
        }

        self.clock_tick()?;
        self.clock_tick()?;

        Ok(())
    }

    /// Advance execution until the next instruction fetch starts or
    /// the machine halts.
    pub fn step_instruction(&mut self) -> Result<(), HardwareError> {
        if self.halted {
            return Ok(());
        }

        self.micro_step()?;

        while !self.halted && self.sequencer_state()[0] != Bit::High {
            self.micro_step()?;
        }

        Ok(())
    }

    /// Run instructions until halted or `max_steps` instructions have
    /// been stepped.
    pub fn run(&mut self, max_steps: usize) -> Result<(), HardwareError> {
        let mut steps = 0;

        while !self.halted && steps < max_steps {
            self.step_instruction()?;
            steps += 1;
        }

        Ok(())
    }

    /// Load a sequence of 8-bit values into RAM starting at address 0.
    pub fn load_program(&mut self, program: &[u8]) -> Result<(), HardwareError> {
        for (address, value) in program.iter().enumerate().take(RAM_REGISTERS) {
            self.ram.write_byte(address, int_to_bits(*value))?;
        }

        Ok(())
    }

    /// Total number of transistors, every sub-component included.
    pub fn transistor_count(&self) -> usize {
        self.program_counter.transistor_count()
            + self.memory_address.transistor_count()
            + self.instruction_register.transistor_count()
            + self.accumulator.transistor_count()
            + self.b_register.transistor_count()
            + self.alu.transistor_count()
            + self.ram.transistor_count()
            + self.sequencer.transistor_count()
            + self.control_unit.transistor_count()
            + self.carry_flag.transistor_count()
            + self.zero_flag.transistor_count()
            + self
                .pc_bus_nmos
                .iter()
                .map(|nmos| nmos.transistor_count())
                .sum::<usize>()
            + self
                .ir_bus_nmos
                .iter()
                .map(|nmos| nmos.transistor_count())
                .sum::<usize>()
            + self
                .acc_bus_nmos
                .iter()
                .map(|nmos| nmos.transistor_count())
                .sum::<usize>()
            + self.pc_or.transistor_count()
            + self.pc_and.transistor_count()
            + self.halt_latch.transistor_count()
            + self.halt_and.transistor_count()
    }

    /// Clock a register on the rising edge; `load` stays LOW so the
    /// outputs stay floating during normal operation.
    fn clock_register(
        &self,
        register: &Register8Bits,
        data: &[Signal; 8],
        clock: Signal,
        save: Bit,
    ) -> Result<(), HardwareError> {
        let mut inputs = [Signal::HighImpedance; Register8Bits::INPUTS];
        inputs[..8].copy_from_slice(data);
        inputs[8] = clock;
        inputs[9] = Signal::from(save);
        inputs[10] = Signal::from(Bit::Low);
        register.conduct_into(
            &inputs,
            &mut [Signal::HighImpedance; Register8Bits::OUTPUTS],
        )?;
        Ok(())
    }

    /// Propagate signals through the combinational and sequential parts
    /// of the machine for the given clock value.
    fn update_at(&mut self, clock: Bit) -> Result<(), HardwareError> {
        let t_states = self.sequencer_state();
        let ir_state = self.instruction_register.state();
        let opcode = [ir_state[4], ir_state[5], ir_state[6], ir_state[7]];
        let (carry_val, zero_val) = self.flags();

        let ctrl = self
            .control_unit
            .control_signals(&t_states, &opcode, carry_val, zero_val)?;

        let clock_signal = Signal::from(clock);
        let low = Signal::from(Bit::Low);

        // Bus drivers. A tri-state transistor whose enable is Low
        // floats its output by itself, so every row is propagated
        // unconditionally and only the active one drives the bus.

        // 1. Program Counter bus (only the four low bits carry the
        //    value, the high half drives constant zeros)
        let mut pc_bus = [Signal::HighImpedance; 8];
        let pc_state = self.program_counter.state();

        for i in 0..8 {
            let source = if i < 4 {
                Signal::from(pc_state[i])
            } else {
                low
            };
            pc_bus[i] = self.pc_bus_nmos[i].conduct(&[Signal::from(ctrl.co), source])?[0];
        }

        // 2. Instruction Register bus (operand on the low 4 bits, zeros
        //    on the high 4 bits)
        let mut ir_bus = [Signal::HighImpedance; 8];

        for i in 0..8 {
            let source = if i < 4 {
                Signal::from(ir_state[i])
            } else {
                low
            };
            ir_bus[i] = self.ir_bus_nmos[i].conduct(&[Signal::from(ctrl.io), source])?[0];
        }

        // 3. Accumulator bus
        let mut acc_bus = [Signal::HighImpedance; 8];
        let acc_state = self.accumulator.state();

        for i in 0..8 {
            acc_bus[i] = self.acc_bus_nmos[i]
                .conduct(&[Signal::from(ctrl.ao), Signal::from(acc_state[i])])?[0];
        }

        // 4. ALU bus & flags (EO drives the ALU output *and* is its
        //    internal `load` input). With `FAST`, an ALU with EO Low
        //    floats its result and its flags by itself; capturing the
        //    floating flags through a save-enabled flip-flop is then
        //    rejected by the hardware, so a micro-state with FI High
        //    but EO Low fails loudly instead of writing stale values.
        let b_state = self.b_register.state();
        let mut alu_inputs = [Signal::HighImpedance; AluSap1::INPUTS];
        for (index, bit) in acc_state.iter().enumerate() {
            alu_inputs[index] = Signal::from(*bit);
        }
        for (index, bit) in b_state.iter().enumerate() {
            alu_inputs[8 + index] = Signal::from(*bit);
        }
        alu_inputs[16] = Signal::from(ctrl.su);
        alu_inputs[17] = Signal::from(ctrl.eo);

        let mut alu_output = [Signal::HighImpedance; AluSap1::OUTPUTS];
        self.alu.conduct_into(&alu_inputs, &mut alu_output)?;
        let alu_bus: [Signal; 8] = alu_output[..8]
            .try_into()
            .expect("the ALU outputs 10 signals");
        let carry_out = alu_output[8];
        let zero_out = alu_output[9];

        // Resolve the partial 8-bit bus (every driver except the RAM)
        // and keep the raw signals: a floating bit stays floating, so
        // sampling it through a save-enabled flip-flop is rejected by
        // the hardware (`HardwareError::InvalidBit`) instead of being
        // silently read as LOW. RI and RO are never both High in the
        // SAP-1 micro-code, so the RAM never fights the other drivers.
        debug_assert!(
            ctrl.ri == Bit::Low || ctrl.ro == Bit::Low,
            "RI and RO are never both High in the SAP-1 micro-code"
        );
        let partial_bus = bus8([pc_bus, ir_bus, acc_bus, alu_bus])?;

        // 5. RAM: one propagation through the memory itself — its own
        //    decoder, save AND gates and tri-state output rows —
        //    performs the write at the rising edge (`save` = RI) and
        //    drives the bus (`load` = RO). No duplicated read circuit
        //    lives in the CPU anymore. With `FAST`, a memory receiving
        //    neither RI nor RO skips itself entirely.
        let mar_state = self.memory_address.state();
        let mut ram_inputs = [Signal::HighImpedance; Ram256Bits::INPUTS];
        ram_inputs[..8].copy_from_slice(&partial_bus);
        for (index, bit) in mar_state[0..4].iter().enumerate() {
            ram_inputs[8 + index] = Signal::from(*bit);
        }
        ram_inputs[12] = clock_signal;
        ram_inputs[13] = Signal::from(ctrl.ri);
        ram_inputs[14] = Signal::from(ctrl.ro);

        let mut ram_row = [Signal::HighImpedance; Ram256Bits::OUTPUTS];
        self.ram.conduct_into(&ram_inputs, &mut ram_row)?;

        let current_bus = bus8([ram_row, partial_bus])?;

        // Sequential clocking. Storage components whose `save` input
        // is Low cannot change state during this tick and skip
        // themselves (see `Register8Bits`), the program counter skips
        // itself while its gated clock is Low (see
        // `ProgramCounter4Bits`) and the halt latch holds while its
        // inputs are Low (see `SRLatch`).
        let pc_clock_enable = self.pc_or.compute(&[ctrl.ce, ctrl.j])?[0];
        let pc_clk = Signal::from(self.pc_and.compute(&[pc_clock_enable, clock])?[0]);

        let mut pc_inputs = [Signal::HighImpedance; ProgramCounter4Bits::INPUTS];
        pc_inputs[..4].copy_from_slice(&current_bus[..4]);
        pc_inputs[4] = pc_clk;
        pc_inputs[5] = Signal::from(ctrl.j);
        pc_inputs[6] = low;
        self.program_counter.conduct_into(
            &pc_inputs,
            &mut [Signal::HighImpedance; ProgramCounter4Bits::OUTPUTS],
        )?;

        self.clock_register(&self.memory_address, &current_bus, clock_signal, ctrl.mi)?;
        self.clock_register(
            &self.instruction_register,
            &current_bus,
            clock_signal,
            ctrl.ii,
        )?;
        self.clock_register(&self.accumulator, &current_bus, clock_signal, ctrl.ai)?;
        self.clock_register(&self.b_register, &current_bus, clock_signal, ctrl.bi)?;

        let mut carry_data = [Signal::from(Bit::Low); 8];
        carry_data[0] = carry_out;
        self.clock_register(&self.carry_flag, &carry_data, clock_signal, ctrl.fi)?;

        let mut zero_data = [Signal::from(Bit::Low); 8];
        zero_data[0] = zero_out;
        self.clock_register(&self.zero_flag, &zero_data, clock_signal, ctrl.fi)?;

        let halt_set = self.halt_and.compute(&[ctrl.hlt, clock])?[0];
        self.halt_latch.conduct(&[Signal::from(halt_set), low])?;

        if self.halt_latch.q() == Bit::High {
            self.halted = true;
        }

        // The sequencer advances on the rising clock edge. It must
        // still be evaluated during the Low tick: each master latch
        // samples the previous flip-flop's output then, and the ring
        // has no `save` input gating the capture.
        self.sequencer.conduct(&[clock_signal])?;

        Ok(())
    }
}

#[cfg(test)]
mod control_unit_tests {
    use super::*;

    #[test]
    fn test_transistor_count() {
        // 1 decoder (152) + 16 AND gates (96) + 13 OR gates (78)
        assert_eq!(ControlUnit::default().transistor_count(), 326);
    }

    #[test]
    fn test_conduct_rejects_wrong_input_count() {
        assert_eq!(
            ControlUnit::default().conduct(&[Signal::from(Bit::Low); 11]),
            Err(HardwareError::InvalidInputCount {
                expected: 12,
                actual: 11,
            })
        );
    }
}

#[cfg(test)]
mod sap1_program_tests {
    use super::*;

    fn run_program(program: &[u8], max_steps: usize) -> Sap1 {
        let mut cpu = Sap1::default();
        cpu.load_program(program).expect("load failed");
        cpu.run(max_steps).expect("run failed");
        cpu
    }

    #[test]
    fn test_transistor_count() {
        let cpu = Sap1::default();
        assert!(cpu.transistor_count() > 0);
    }

    #[test]
    fn test_nop_instruction() {
        let cpu = run_program(&[0x00, 0xF0], 100); // NOP, HLT
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 0);
    }

    #[test]
    fn test_ldi_instruction() {
        let cpu = run_program(&[0x5A, 0xF0], 100); // LDI 10, HLT
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 10);
    }

    #[test]
    fn test_lda_and_sta_instructions() {
        // LDI 7, STA 0xA, LDI 0, LDA 0xA, HLT
        let cpu = run_program(&[0x57, 0x4A, 0x50, 0x1A, 0xF0], 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 7);
    }

    #[test]
    fn test_add_instruction() {
        // LDI 5, ADD 0xE, HLT (mem[0xE] = 3)
        let mut program: Vec<u8> = vec![0x55, 0x2E, 0xF0];
        program.extend(std::iter::repeat_n(0, 11));
        program.extend([3, 0]);

        let cpu = run_program(&program, 100);

        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 8);
    }

    #[test]
    fn test_sub_instruction() {
        // LDI 9, SUB 0xE, HLT (mem[0xE] = 4)
        let mut program: Vec<u8> = vec![0x59, 0x3E, 0xF0];
        program.extend(std::iter::repeat_n(0, 11));
        program.extend([4, 0]);

        let cpu = run_program(&program, 100);

        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 5);
    }

    #[test]
    fn test_jmp_instruction() {
        // 0: JMP 3, 1: LDI 9 (skipped), 2: HLT, 3: LDI 4, 4: HLT
        let cpu = run_program(&[0x63, 0x59, 0xF0, 0x54, 0xF0], 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 4);
    }

    fn with_operand_at_e(program: &[u8], operand: u8) -> Vec<u8> {
        let mut full: Vec<u8> = program.to_vec();
        full.resize(14, 0);
        full.extend([operand, 0]); // mem[0xE] = operand
        full
    }

    #[test]
    fn test_jz_taken() {
        // 0: LDI 3, 1: SUB 0xE (3 - 3 = 0), 2: JZ 5, 3: LDI 9,
        // 4: HLT, 5: LDI 6, 6: HLT
        let program = with_operand_at_e(&[0x53, 0x3E, 0x75, 0x59, 0xF0, 0x56, 0xF0], 3);
        let cpu = run_program(&program, 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 6);
    }

    #[test]
    fn test_jz_not_taken() {
        // 0: LDI 4, 1: SUB 0xE (4 - 3 = 1), 2: JZ 5 (not taken),
        // 3: LDI 9, 4: HLT
        let program = with_operand_at_e(&[0x54, 0x3E, 0x75, 0x59, 0xF0, 0x56, 0xF0], 3);
        let cpu = run_program(&program, 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 9);
    }

    #[test]
    fn test_jc_taken() {
        // 0: LDI 10, 1: ADD 0xE (10 + 250 = 260 -> carry), 2: JC 5,
        // 3: LDI 9, 4: HLT, 5: LDI 6, 6: HLT
        let program = with_operand_at_e(&[0x5A, 0x2E, 0x85, 0x59, 0xF0, 0x56, 0xF0], 250);
        let cpu = run_program(&program, 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 6);
    }

    #[test]
    fn test_jc_not_taken() {
        // 0: LDI 2, 1: ADD 0xE (2 + 3 = 5, no carry), 2: JC 5 (not taken)
        let program = with_operand_at_e(&[0x52, 0x2E, 0x85, 0x59, 0xF0, 0x56, 0xF0], 3);
        let cpu = run_program(&program, 100);
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 9);
    }

    #[test]
    fn test_loop_multiplication_program() {
        // Multiply 3 by 5 using a loop.
        let program = [
            0x1F, // 0: LDA 0xF (load accumulator / running sum)
            0x2E, // 1: ADD 0xE (add 3)
            0x4F, // 2: STA 0xF (store back to running sum)
            0x1D, // 3: LDA 0xD (load count)
            0x3C, // 4: SUB 0xC (subtract 1)
            0x79, // 5: JZ 9 (if count reached 0, jump to 9)
            0x4D, // 6: STA 0xD (save decremented count)
            0x60, // 7: JMP 0 (loop back to LDA 0xF)
            0x00, // 8: NOP
            0x1F, // 9: LDA 0xF (load final sum)
            0xF0, // A: HLT
            0x00, // B: unused
            0x01, // C: constant 1
            0x05, // D: initial count = 5
            0x03, // E: constant 3
            0x00, // F: sum initialized to 0
        ];

        let cpu = run_program(&program, 500);

        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 15);
    }

    #[test]
    fn test_clock_tick_and_micro_step() {
        let mut cpu = Sap1::default();
        cpu.load_program(&[0x57, 0xF0]).expect("load failed"); // LDI 7, HLT

        // Advance step by step using clock_tick.
        assert_eq!(cpu.clock(), Bit::Low);
        assert_eq!(cpu.clock_tick().expect("clock tick failed"), Bit::High);
        assert_eq!(cpu.clock_tick().expect("clock tick failed"), Bit::Low);

        // Run with micro_step.
        cpu.micro_step().expect("micro step failed");
        assert!(!cpu.halted());

        cpu.run(100).expect("run failed");
        assert!(cpu.halted());
        assert_eq!(bits_to_int(&cpu.out(), false), 7);
    }

    #[test]
    fn test_halted_clock_stops() {
        let mut cpu = Sap1::default();
        cpu.load_program(&[0xF0]).expect("load failed"); // HLT only
        cpu.run(10).expect("run failed");
        assert!(cpu.halted());

        // Once halted, the clock no longer toggles.
        let clock_before = cpu.clock();
        cpu.clock_tick().expect("clock tick failed");
        assert_eq!(cpu.clock(), clock_before);
    }
}
